name: Build and Deploy to ECS

on:
   workflow_dispatch

jobs:
  build_and_deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        
        ls
        cd ecs
        docker build -t dhayaanand71/microservice:custommicroservice -f Dockerfile .

    # - name: Push Docker image to Docker Hub
    #   run: |
    #     docker push dhayaanand71/microservice:custommicroservice

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-east-1

    - name: Deploy Docker image to ECS
      run: |
        ecs_task_definition=$(aws ecs register-task-definition \
          --family microservice-task \
          --network-mode awsvpc \
          --cpu 256 \
          --memory 512 \
          --execution-role-arn arn:aws:iam::123456789012:role/ecsTaskExecutionRole \
          --task-role-arn arn:aws:iam::123456789012:role/ecsTaskExecutionRole \
          --container-definitions "[{\"name\":\"microservice\",\"image\":\"your-dockerhub-account/microservice:custommicroservice\",\"essential\":true,\"portMappings\":[{\"containerPort\":3000,\"hostPort\":3000}]}]" \
          --query 'taskDefinition.taskDefinitionArn' --output text)
        
        aws ecs update-service \
          --cluster ecs-cluster \
          --service microservice-service \
          --task-definition $ecs_task_definition
